spring:
  cloud:
    gateway:
      routes:
        - id: clients-service
          uri: lb://clients-service
          predicates:
            - Path=/api/clients/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
security:
  jwt:
    key:
      private: 2dd57dfe27e671d7fad1d9517900518607dfb1d0a4718105b2e69986349d0a83

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka